# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Utilisation d'un runner Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'temurin' # AdoptOpenJDK est maintenant Eclipse Temurin
    - name: Build with Ant
      # Assurez-vous que le fichier build.xml est présent à la racine de votre projet
      run: ant -noinput -buildfile build.xml
